# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queriesapp', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
