# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queriesapp', '0013_auto_20171203_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('upload_time', models.DateTimeField()),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queriesapp.Post')),
            ],
        ),
    ]
